
app:
  name: typexs-server


server:
  default:
    type: web
    framework: express
    host: localhost
    port: 4500

    routes:
    - type: routing_controller
      context: api
      routePrefix: api


logging:
  enable: true
  level: debug
  transports:
  - console: {}


