import { Container } from "typedi";
import { IActivator, IPermissions} from "@typexs/base";
import {ServerRegistry} from "./libs/server/ServerRegistry";
import {
  PERMISSION_ALLOW_ACCESS_STORAGE_ENTITY,
  PERMISSION_ALLOW_ACCESS_STORAGE_ENTITY_PATTERN, PERMISSION_ALLOW_ACCESS_STORAGE_METADATA,
  PERMISSION_ALLOW_DELETE_STORAGE_ENTITY,
  PERMISSION_ALLOW_DELETE_STORAGE_ENTITY_PATTERN,
  PERMISSION_ALLOW_GLOBAL_CONFIG_VIEW,
  PERMISSION_ALLOW_MODULES_VIEW,
  PERMISSION_ALLOW_ROUTES_VIEW,
  PERMISSION_ALLOW_SAVE_STORAGE_ENTITY,
  PERMISSION_ALLOW_SAVE_STORAGE_ENTITY_PATTERN,
  PERMISSION_ALLOW_STORAGE_ENTITY_VIEW,
  PERMISSION_ALLOW_STORAGES_VIEW,
  PERMISSION_ALLOW_UPDATE_STORAGE_ENTITY,
  PERMISSION_ALLOW_UPDATE_STORAGE_ENTITY_PATTERN
} from "./libs/Constants";


export class Activator implements IActivator, IPermissions {


  async startup() {
    let serverRegistry = new ServerRegistry();
    Container.set(ServerRegistry, serverRegistry);
    Container.set('ServerRegistry', serverRegistry);
  }

  permissions(): string[] {
    return [
      PERMISSION_ALLOW_ROUTES_VIEW,
      PERMISSION_ALLOW_MODULES_VIEW,
      PERMISSION_ALLOW_GLOBAL_CONFIG_VIEW,
      PERMISSION_ALLOW_STORAGES_VIEW,
      PERMISSION_ALLOW_STORAGE_ENTITY_VIEW,

      PERMISSION_ALLOW_ACCESS_STORAGE_METADATA,
      PERMISSION_ALLOW_ACCESS_STORAGE_ENTITY,
      PERMISSION_ALLOW_ACCESS_STORAGE_ENTITY_PATTERN,
      PERMISSION_ALLOW_SAVE_STORAGE_ENTITY,
      PERMISSION_ALLOW_SAVE_STORAGE_ENTITY_PATTERN,
      PERMISSION_ALLOW_UPDATE_STORAGE_ENTITY,
      PERMISSION_ALLOW_UPDATE_STORAGE_ENTITY_PATTERN,
      PERMISSION_ALLOW_DELETE_STORAGE_ENTITY,
      PERMISSION_ALLOW_DELETE_STORAGE_ENTITY_PATTERN
    ]
  }

}
